[build]
  functions = "netlify/functions"
  command = "cd netlify/functions && npm install"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/validate"
  to = "/.netlify/functions/validate"
  status = 200

[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/generate"
  status = 200

[[redirects]]
  from = "/api/lookup"
  to = "/.netlify/functions/lookup"
  status = 200
